policy:
  enabled: true
  subjectRegExp: '^https://github[.]com/paulacristinaqa/automotive_test_engineering_platform/[.]github/workflows/reusable-release-builder[.]yml@refs/heads/main$'
  predicateType: https://slsa.dev/provenance/v1
  images:
    - 'ghcr.io/paulacristinaqa/automotive_test_engineering_platform**'
  exemptImages: []
  trust:
    github: true
    sigstorePublic: true
    githubTrustDomain: ''
